[project]
name = "digitwins-mqtt"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = ">=3.9,<3.12"
paho-mqtt = "*"
jupyter = "*"
ipykernel = "*"
obstore = "*"
polars = "*"
deltalake = "*"
pyarrow = "*"
